### ISSUE TITLE
⚒️ API serving Health check at `Part 8. Stream`

### ISSUE THREAD

**Issue by Kimdongui** [mlops-for-mle/mlops-for-mle#28]
## Is your feature request related to a problem? Please describe.
- API serving container 가 잘 작동 할 때까지 health check 필요

**Comment by dongminlee94** [comment]
> ## Is your feature request related to a problem? Please describe.
> * API serving container 가 잘 작동 할 때까지 health check 필요

@Kimdongui  굳이 할 필요 있을까요? 저는 없어도 될 것 같아요.

**Comment by Kimdongui** [comment]
@dongminlee94 해당 내용은 [다음 PR](https://github.com/mlops-for-mle/tutorial/pull/16)의 내용을 보시면
> stream 에서 model api 랑 subscriber 를 같이 실행하면 model api 가 아직 준비가 안되서 뻑나고 죽는 경우가 발생합니다!

라는 내용이 있어서 필요하게 되었습니다 :)

**Comment by Kimdongui** [comment]
좀 더 명확하게 이슈 제목 수정했습니다!

**Comment by dongminlee94** [comment]
> @dongminlee94 해당 내용은 [다음 PR](https://github.com/mlops-for-mle/tutorial/pull/16)의 내용을 보시면
> 
> > stream 에서 model api 랑 subscriber 를 같이 실행하면 model api 가 아직 준비가 안되서 뻑나고 죽는 경우가 발생합니다!
> 
> 라는 내용이 있어서 필요하게 되었습니다 :)

아 그렇군요 `depends_on` option 을 넣었는데도 그러던가요?

**Comment by Kimdongui** [comment]
음.. 제가 확인한건 아니고 종섭님이 발견하셨습니다!

@Aiden-Jeon 종섭님 `depends_on` 으로 순서를 맞춰 띄워도 발생하셨나요?

**Comment by Aiden-Jeon** [comment]
> 음.. 제가 확인한건 아니고 종섭님이 발견하셨습니다!
> 
> @Aiden-Jeon 종섭님 `depends_on` 으로 순서를 맞춰 띄워도 발생하셨나요?

네 depends on 은 프로세스 실행 여부만 따져서.. uvicorn 이 켜지는 순간 다음 프로세스로 넘어갑니다
이 때 subscriber 가 request 를 요청하는데 fastapi 에서 해당 요청을 처리 못해서 다 종료됩니다.

**Comment by Kimdongui** [comment]
해결 되었습니다.
