### ISSUE TITLE
document와 code가 다른 부분이 있어요

### ISSUE THREAD

**Issue by parkkyungjun** [mlops-for-mle/mlops-for-mle#45]
02. Model Development
db_train.py, db_validate_save_model

부분에서, 
X = df.drop(["id", "target"], axis="columns") doc에는 이렇게 되어 있고
code 에는 
X = df.drop(["id", "target", "timestamp"], axis="columns")
이렇게 되어 있어요

그리고 

01. database
파트에서 select * from iris_data; 이 명령어를 통해 table을 보여주실때,

 id   | sepal_length   | sepal_width  | petal_length   | petal_width   | target 
----+--------------+-------------+--------------+-------------+--------
  1    |          6.7          |                    3 |            5           |         1.7          |      1

이런식으로 표현주셨는데,

timestamp column이 빠진것 같아요

**Comment by ChaejinE** [comment]
```
TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. 
This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. 
The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>)
```

저도 같은 Part에서 에러가 났었습니다.
drop에서 timestamp를 추가하니 정상적으로 동작했습니다. timestamp의 데이터타입이 postgresql에서 뭔가 명확하지 않아보입니다. 따라서 timestamp column을 drop하는게 맞아보입니다.

**Comment by parkkyungjun** [comment]
넹 저도 그렇게 생각해요

**Comment by parkkyungjun** [comment]
> ```
> TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. 
> This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. 
> The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>)
> ```
> 
> 저도 같은 Part에서 에러가 났었습니다. drop에서 timestamp를 추가하니 정상적으로 동작했습니다. timestamp의 데이터타입이 postgresql에서 뭔가 명확하지 않아보입니다. 따라서 timestamp column을 drop하는게 맞아보입니다.

넹 저도 그렇게 생각해요

**Comment by Kimdongui** [comment]
안녕하세요! 의견 달아주셨는데 대응이 늦었습니다 😭  다시 오픈해서 관련된 PR 올리겠습니다!
의견 진심으로 감사합니다. 🙏

**Comment by Kimdongui** [comment]
@ChaejinE @parkkyungjun
문서 repository 의 다음 [PR](https://github.com/mlops-for-mle/tutorial/pull/81)으로 해결 되었습니다 :)
다시 한번 의견 감사합니다!
