### ISSUE TITLE
[Fail] minio healthy check

### ISSUE THREAD

**Issue by brianjang** [mlops-for-mle/mlops-for-mle#47]
## Describe the bug
[Part3] minio health check 가 실패함

## To Reproduce
관련 파일: https://github.com/mlops-for-mle/mlops-for-mle/blob/main/part3/docker-compose.yaml
- healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]

## Expected behavior
 ✔ Network part3_default            Created                                                                                                                                                                                    0.1s 
 ✔ Container mlflow-artifact-store  Healthy                                                                                                                                                                                    0.2s 
 ✔ Container mlflow-backend-store   Healthy                                                                                                                                                                                    0.2s 
 ✔ Container mlflow-server          Started  

아래 링크를 참고하여 healthcheck 부분 수정 후 성공
`healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
`
https://github.com/ems-project/elasticms-web-docker/commit/b895c1e9cad066c3de00538f7c1ab0f89fb9d174

**Comment by dongminlee94** [comment]
@brianjang 안녕하세요.
이슈 남겨주셔서 감사합니다. :) 

@Kimdongui 동현님 part3 mlflow 쪽인데 확인가능하실까요~?

**Comment by Kimdongui** [comment]
상세하게 방법도 남겨주셔서 감사합니다!

**Comment by Kimdongui** [comment]
@brianjang 반영되어서 Close 하겠습니다 :)
다시한번 이슈 감사드립니다!
